### PR TITLE
This is fine

### PR DESCRIPTION
**Pull request by nivlac12**

### CODE REVIEW

**Comment by AlbertSnows** [comment]
LGTM

**Review by burace17 — APPROVED** [review]
LGTM

**Comment by AlbertSnows** [comment]
> LGTM

🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔

**Review by AlbertSnows — CHANGES_REQUESTED** [review]
replace it with the entire source code of amazon and it should be good

**Comment by Trosclair** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢀⡤⠒⠉⠉⠁⠀⠈⠉⠓⢦⣀⠀⠀⠀
⠀⠀⠀⠀⠀⢀⡴⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢷⡄⠀
⠀⠀⠀⠀⢀⡞⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⡄
⠀⠀⠀⠀⣸⠀⣠⠞⠋⠛⣆⠀⠀⢀⡤⠴⢦⣄⠀⠀⠀⣿
⠀⠀⠀⠀⣿⢠⡏⠀⠀⡀⢸⠀⢠⠏⠀⠀⠀⠙⣦⠀⠀⣼
⠀⠀⠀⠀⠸⣸⡃⠀⠀⡇⢸⠀⣼⢰⣷⠀⠀⠀⢸⠇⠀⡟
⠀⠀⠀⠀⠀⢳⣳⣤⣀⣀⡾⠀⠻⣄⠁⠀⠀⣠⠎⢀⡾⠁
⠀⠀⠀⠀⠀⠀⠑⢭⡛⠋⠀⠀⠀⠩⢟⣿⠛⢁⡤⠊⠀⠀
⠀⠀⣠⣲⡤⣄⣀⠀⠈⠑⠂⠤⠤⠤⠤⠒⠊⠁⠀⠀⠀⠀
⣿⡟⠍⠨⠐⠃⠘⣽⣤⠄⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠉⠙⡄⠀⠀⠀⠀⢹⡏⠀⠀⠀⠀⠉⠉⠐⢒⡒⠠⣤⠀⠀
⠀⠀⠘⡆⠀⠀⠀⢘⣇⣠⡤⠤⠄⢀⣀⣀⠤⣪⠝⠁⠀⠀
⠀⠀⠀⠉⠲⠤⣁⡼⠀⠀⠈⠉⠉⠉⠉⠉⠉⠀⠀⠀⠀⠀

**Pull request closed without merging**
